### ISSUE TITLE
how to successfully load the driver

### ISSUE THREAD

**Issue by lpxnvk** [hvmi/hvmi#14]
bsod on windows when I load introbootdrv.sys and introvecore.sys . is there a document with the correct loading steps?
I found that most of the practical functions are designed internally, such as hooks. If you use it, you must modify hvmi. Is it possible to provide an external interface like callback? thanks

**Comment by vlutas** [comment]
How are you trying to load these drivers? They are not designed to be loaded manually, and can only be injected dynamically by Introcore.

**Comment by abuda-bd** [comment]
Hi there. The 2 drivers (introbootdrv.sys and introvecore.sys) are what we call Agents (you can learn more about them here https://hvmi.readthedocs.io/en/latest/chapters/7-agents-architecture.html).
•	introbootdrv.sys – is an agent aimed to reduce the semantic (provide functionality that would otherwise be very difficult if not impossible to implement such as dropping a file inside the guest VM). https://hvmi.readthedocs.io/en/latest/_static/doxygen/html/winagent_8c.html#details
•	introvecore.sys – is an agent used on #VE capable processors, its purpose being to increase performance by receiving #VE exceptions (on convertible pages) inside the guest rather than EPT violations and forward only the “needed” violations to the guest. https://hvmi.readthedocs.io/en/latest/chapters/7-agents-architecture.html#special-agents
As you may see, both of them communicate with the HV using hypercalls so loading them separately will not work.

**Comment by lpxnvk** [comment]
> How are you trying to load these drivers? They are not designed to be loaded manually, and can only be injected dynamically by Introcore.

 i use [DrvLoader](https://github.com/tandasat/DrvLoader)  to load driver file.
> DrvLoader introbootdrv.sys
How to inject, don’t I need to load the driver? I wrongly thought that the driver needs to be loaded like [HyperPlatform](https://github.com/tandasat/HyperPlatform)

**Comment by lpxnvk** [comment]
> Hi there. The 2 drivers (introbootdrv.sys and introvecore.sys) are what we call Agents (you can learn more about them here https://hvmi.readthedocs.io/en/latest/chapters/7-agents-architecture.html).
> • introbootdrv.sys – is an agent aimed to reduce the semantic gap (provide functionality that would otherwise be very difficult if not impossible to implement - such as dropping a file inside the guest VM). https://hvmi.readthedocs.io/en/latest/_static/doxygen/html/winagent_8c.html#details
> • introvecore.sys – is an agent used on #VE capable processors, its purpose being to increase performance by receiving #VE exceptions (on convertible pages) inside the guest rather than EPT violations and forward only the “needed” violations to the guest. https://hvmi.readthedocs.io/en/latest/chapters/7-agents-architecture.html#special-agents
> As you may see, both of them are designed to work/communicate with the HV/HVMI and are injected by HVMI in the guest VM, so loading them with various scripts or OsrLoader will not work.

so how can I make these drivers run normally, and then debugging. I ran introagentkiller_agent.exe/introagent_agent.exe but nothing changed.

**Comment by vlutas** [comment]
Hello,

So first thing, it is very important to understand that these are **not** drivers (at least not regular drivers as you would expect to see in a normal Windows OS). These modules (introbootdrv.sys and introvecore.sys) are special binaries which can only be loaded by the introspection engine (they are injected inside the guest at runtime - they can't be loaded inside the guest any other way) dynamically - we call them **agents**, and they are loaded from outside of the guest VM. It is impossible for them to be loaded any other way.
Secondly, the introspection engine doesn't need any kind of driver to be present inside the guest OS. It runs perfectly fine without any help from inside the guest OS. 
Finally, the introspection engine has several features which allows it to run code inside the guest. One of these features is starting a process inside the guest OS. Another feature is using the #VE (Virtualization Exception) to improve performance - the modules listed above are used for this purpose, but like already mentioned, they can only be dynamically injected by the introspection engine, and they cannot be installed or started in the guest like regular drivers. Even in this case, only the introspection engine can decide whether the modules need to be injected inside the guest or not.

Hopefully this clarifies the things a bit.

Best regards!

**Comment by lpxnvk** [comment]
@vlutas  thank you for your detailed explanation, so how do I install and test this project.how to build a running and debugging environment.

**Comment by vlutas** [comment]
Hello,

The project readme (https://github.com/hvmi/hvmi/blob/master/README.md) provides a good overview of how to get things up. The following blog posts provide step-by-step details on how to build an environment & start running HVMI - https://hvmi.github.io/blog/2020/08/10/getting-started-on-Xen.html (for Xen) and https://hvmi.github.io/blog/2020/08/10/getting-started-on-kvm.html (for KVM).

Best regards!

**Comment by lpxnvk** [comment]
Thanks, it is very useful👍
