### ISSUE TITLE
r2cami doesn't add syscall offset

### ISSUE THREAD

**Issue by logankonopatzke** [hvmi/hvmi#24]
Currently, r2cami generates guest support files without an 'offset' member for '!syscall_pattern'. This will cause an error when generating the binary file.

Output: `AttributeError: 'SyscallPattern' object has no attribute 'offset'`

**Comment by logankonopatzke** [comment]
This will be fixed by #25.

**Comment by vlutas** [comment]
The PR has been merged, so feel free to close this at your convenience.

**Comment by logankonopatzke** [comment]
Fixed by #25.
