### ISSUE TITLE
[Question] About achieve a custom VeCoreVirtualizationExceptionHandler

### ISSUE THREAD

**Issue by L1B0** [hvmi/hvmi#71]
Hi, I'm learning how to accomplish a #VE handler, as well as reading the code in hvmi.

I tried to write a #VE handler in my hypervisor. When I test it, it is just executed once time, and then all EPT violation caused VM-Exits.

By the way, it just log Exit Qualification in #VE handler.

Do you meet any similar situations? And do you know how to debug the hypervisor in #VE handler.

Thanks a lot.

**Comment by vlutas** [comment]
Hello,

Thanks for being interested in HVMI! :)

When a #VE is delivered, the CPU will write the value 0xFFFFFFFF at offset 4 in the #VE information page. As long as that field remains 0xFFFFFFFF, no other #VEs can be delivered. The solution is quite simple: make sure you store a 0 at offset 4 in the #VE info page before you IRET from the #VE handler (check out Intel SDM, Volume 3C, Chapter 25, Section 25.5.7.1 for more info).

Cheers!

**Comment by L1B0** [comment]
I have seen the Reserved element in _VECPU struct and its comment hhh.
```
 DWORD           Reserved;               ///< Reserved. This field will be set to 0xFFFFFFFF when a VE is delivered.
                                            ///< If this field is 0xFFFFFFFF, the CPU will not generate VEs anymore;
                                            ///< instead, EPT violations will be delivered as usual.
```

If I want to cause #VE when every EPT violation causes, I should set the Reserved to 0 when #VE handler is firstly exeuted.

**Comment by L1B0** [comment]
Hi, I have a new question, after I set the Reserved field to 0 in VE handler, my guest is hanged out, and the bug value is NMI_HARDWARE_FAILURE(80).

And I have seen the details by analysing dmp file in windbg, I don't understand the bug value well.

Do you know something about that?

Thanks!

**Comment by L1B0** [comment]
Yeah, I wrote custom code, not from hvmi repo.

And before I set the Reserved field to 0 in VE handler, the guest doesn't hang out.

By the way, do you know how to debug this kind of issue in hypervisor, as well as windbg doesn't locate it in my hypervisor source code but in kernel code? 

I think maybe a reason is that I set a write hook to a kernel data page, and I don't accomplish guest's write access in the #VE handler function by emulating its.

**Comment by vlutas** [comment]
> I think maybe a reason is that I set a write hook to a kernel data page, and I don't accomplish guest's write access in the #VE handler function by emulating its.

This may be your problem. You'd have to emulate whatever access generated the #VE, otherwise bad things will happen to the OS (crash, hang, etc.).
As for debugging it - that depends entirely on your architecture. Are you running bare metal (Type 1), or hosted (Type 2) HV? Are you running it on physical hardware, or inside a VM (using nested VT-x)?

**Comment by L1B0** [comment]
Yeah, I'm running Type1 HV inside Win10 by VMware, which is using nested VT-x.

When it is executing code in HV, if I debug it with windbg, windbg doesn't have breakpoint, so I don't know how can debug it.

I have seen using bochs maybe a feasible way, but it is too slow.

Thanks!

**Comment by L1B0** [comment]
I have known how to debug type1 hyperv by vmware.

Reference to https://www.triplefault.io/2017/07/setup-vmm-debugging-using-vmwares-gdb_9.html. 

It's very fast and simple to use.
